CmkFurnitures.Web.UI/Areas/Admin/Controllers/StoreDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CmkFurnitures.Domain.Services;
using CmkFurnitures.Web.UI.Areas.Admin.Models;
using CmkFurnitures.Domain.Models;

namespace CmkFurnitures.Web.UI.Areas.Admin.Controllers
{
    public class StoreDetailsController : BaseController
    {
        IStoreDetailService StoreDetailService;
        public StoreDetailsController(IStoreDetailService storeDetailService)
        {
            this.StoreDetailService = storeDetailService;
        }

        //
        // GET: /Admin/StoreDetails/

        public ActionResult Index()
        {
            StoreDetails storeDetails = StoreDetailService.GetStoreDetails();

            return View(new IndexStoreDetailsViewModel
            {
                StoreDetails = storeDetails,
                Name = storeDetails.Name,
                Address = new IndexStoreDetailsViewModel.AddressInformation
                {
                    Number = storeDetails.Address.Number,
                    Postal = storeDetails.Address.Postal,
                    Road = storeDetails.Address.Road,
                    Town = storeDetails.Address.Town
                },
                Contact = new IndexStoreDetailsViewModel.ContactInformation
                {
                    Email = storeDetails.Contact.Email,
                    Mobilephone = storeDetails.Contact.Mobilephone,
                    Telephone = storeDetails.Contact.Telephone
                }
            });
        }


        //
        // POST: /Admin/StoreDetails/

        [HttpPost]
        public ActionResult Update(IndexStoreDetailsViewModel requestedViewModel)
        {
            List<int> openingHours = new List<int>();
            ValidateOpeningHours(requestedViewModel.OpeningHour, "OpeningHour", ref openingHours);

            List<int> closingHours = new List<int>();
            ValidateOpeningHours(requestedViewModel.CloseingHour, "CloseingHour", ref closingHours);

            if (ModelState.IsValid)
            {
                StoreDetails storeDetails = new StoreDetails();

                storeDetails.Name = requestedViewModel.Name;

                storeDetails.Address = new StoreDetails.AddressInformation
               {
                   Number = requestedViewModel.Address.Number,
                   Postal = requestedViewModel.Address.Postal,
                   Road = requestedViewModel.Address.Road,
                   Town = requestedViewModel.Address.Town
               };

                storeDetails.Contact = new StoreDetails.ContactInformation
                {
                    Email = requestedViewModel.Contact.Email,
                    Mobilephone = requestedViewModel.Contact.Mobilephone,
                    Telephone = requestedViewModel.Contact.Telephone
                };

                for (int i = 0; i < 7; i++)
                {
                    storeDetails.OpeningHours.Add(new StoreDetails.OpeningHour
                    {
                        Day = i,
                        Closeing = closingHours.ElementAt(i),
                        Opening = openingHours.ElementAt(i)
                    });
                }

                StoreDetailService.Update(storeDetails);
            }

            return RedirectToAction("Index");
        }

        private void ValidateOpeningHours(IEnumerable<string> hours, string name, ref List<int> list)
        {
            for (var i = 0; i < hours.Count(); i++)
            {
                string modelName = name + "[" + i + "]", obj = hours.ElementAt(i);

                if (string.IsNullOrWhiteSpace(obj))
                {
                    ModelState.AddModelError(modelName, "Må ikke være tom");
                }

                int openingHour;
                if (!int.TryParse(obj, out openingHour))
                {   
                    ModelState.AddModelError(modelName, "Skal være et heltal");
                }
                else
                {
                    if ((openingHour < 0 || openingHour > 2359) && (openingHour != -1))
                    {
                        ModelState.AddModelError(modelName, "Tallet skal være imellem 0 og 2359");
                    }
                }
                if (ModelState.IsValid)
                {
                    list.Add(openingHour);
                }
            }
        }

    }
}

CmkFurnitures.Web.UI/Areas/Admin/Views/StoreDetails/Index.cshtml
@model CmkFurnitures.Web.UI.Areas.Admin.Models.IndexStoreDetailsViewModel
@{
    ViewBag.Title = "Index";
}
@using (Html.BeginForm("Update", "StoreDetails", FormMethod.Post, new { @class = "form-horizontal" }))
{
    <fieldset>
        <legend>Informationer</legend>
        <div class="control-group">
            <label class="control-label">
                Navn:
            </label>
            <div class="controls">
                @Html.TextBoxFor(x => x.Name)
                @Html.ValidationMessageFor(x => x.Name)
            </div>
        </div>
    </fieldset>
    <fieldset>
        <legend>Addresse</legend>
        <div class="control-group">
            <label class="control-label">
                Vejnavn:
            </label>
            <div class="controls">
                @Html.TextBoxFor(x => x.Address.Road)
                @Html.ValidationMessageFor(x => x.Address.Road)
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">
                Nummer:
            </label>
            <div class="controls">
                @Html.TextBoxFor(x => x.Address.Number)
                @Html.ValidationMessageFor(x => x.Address.Number)
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">
                Postnummer:
            </label>
            <div class="controls">
                @Html.TextBoxFor(x => x.Address.Postal)
                @Html.ValidationMessageFor(x => x.Address.Postal)
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">
                Bynavn:
            </label>
            <div class="controls">
                @Html.TextBoxFor(x => x.Address.Town)
                @Html.ValidationMessageFor(x => x.Address.Town)
            </div>
        </div>
    </fieldset>
    <fieldset>
        <legend>Kontaktoplysninger</legend>
        <div class="control-group">
            <label class="control-label">
                Email:
            </label>
            <div class="controls">
                @Html.TextBoxFor(x => x.Contact.Email)
                @Html.ValidationMessageFor(x => x.Contact.Email)
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">
                Telefon nr.:
            </label>
            <div class="controls">
                @Html.TextBoxFor(x => x.Contact.Telephone)
                @Html.ValidationMessageFor(x => x.Contact.Telephone)
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">
                Mobil nr.:
            </label>
            <div class="controls">
                @Html.TextBoxFor(x => x.Contact.Mobilephone)
                @Html.ValidationMessageFor(x => x.Contact.Mobilephone)
            </div>
        </div>
    </fieldset>
    <fieldset>
        <legend>Åbningstider</legend>
        @for (var i = 0; i < 7; i++)
        {
            var hour = Model.StoreDetails.GetOpenHourByDayIndex(i);
            string opening = "", closeing = "";
            if (hour != null)
            {
                opening = hour.Opening.ToString();
                closeing = hour.Closeing.ToString();
            }

            bool isOpen = (hour.Opening >= 0 && hour.Closeing >= 0);

            string checkBoxId = "openClose_" + i;
            string textBoxContainerId = "txtContainerOpenClose_" + i;

            object htmlAttributes = null;
            if (!isOpen)
            {
                htmlAttributes = new { disabled = "disabled" };
            }
            <div class="control-group">
                <label class="control-label">
                    @Html.TranslateEnglishDay(i, "da-DK"):
                </label>
                <div class="controls controls-row">
                    <div class="span5" id="@textBoxContainerId">
                        @Html.TextBox("OpeningHour[" + i + "]", opening, htmlAttributes)
                        @Html.ValidationMessage("OpeningHour[" + i + "]")
                        til
                        @Html.TextBox("CloseingHour[" + i + "]", closeing, htmlAttributes)
                        @Html.ValidationMessage("CloseingHour[" + i + "]")
                    </div>
                    <div class="span4">
                        <label class="checkbox inline">
                            <input type="radio" name="@checkBoxId" data-container="#@textBoxContainerId" @if (isOpen)
                                                                                                         { <text>checked="checked"</text> } class="checkbox-field" value="open" />
                            Åben
                        </label>
                        <label class="checkbox inline">
                            <input type="radio" name="@checkBoxId" data-container="#@textBoxContainerId" @if (!isOpen)
                                                                                                         { <text>checked="checked"</text> } class="checkbox-field" value="closed" />
                            Lukket
                        </label>
                    </div>
                </div>
            </div>            
        }
    </fieldset>
    <div class="form-actions">
        <button type="submit" class="btn btn-primary">
            Gem ændringer</button>
    </div>
}
@section CustomJavascript{
    <script>
        $(function () {
            $(".checkbox-field").change(function (e) {
                var $this = $(this),
                    isOpen = ($this.val() === "closed") ? false : true;

                if (isOpen) {
                    $($this.data("container") + " > input")
                        .val("")
                        .removeClass("uneditable-input")
                        .removeAttr("readonly");
                } else {
                    $($this.data("container") + " > input")
                        .val("-1")
                        .attr("readonly", "readonly")
                        .addClass("uneditable-input");
                }
            });
        });
    </script>
}