CmkFurnitures.Web.UI/Models/RandomFurnitureViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using CmkFurnitures.Domain;

namespace CmkFurnitures.Web.UI.Models
{
    public class RandomFurnitureViewModel
    {
        public Furniture Furniture { get; set; }
    }
}

CmkFurnitures.Web.UI/Areas/Admin/Controllers/FurnituresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using CmkFurnitures.Web.UI.Areas.Admin.Models;
using CmkFurnitures.Domain.Services;
using CmkFurnitures.Domain;
using System.ComponentModel.DataAnnotations;
using System.Runtime.InteropServices;

namespace CmkFurnitures.Web.UI.Areas.Admin.Controllers
{
    [Authorize]
    public class FurnituresController : BaseController
    {
        protected IFurnitureService FurnitureService;
        protected IImageService ImageService;

        public FurnituresController(IFurnitureService funitureService, IImageService imageService)
        {
            this.FurnitureService = funitureService;
            this.ImageService = imageService;
        }

        //
        // GET: /Admin/Furnitures/

        public ActionResult Index()
        {
            return View(new IndexFurnituresViewModel
            {
                Furnitures = FurnitureService.GetAll()
            });
        }

        //
        // GET: /Admin/Furnitures/Create

        public ActionResult Create()
        {
            return View(new CreateFurnituresViewModel
            {
                FurnitureForm = new FurnitureFormViewModel
                {
                    Designers = FurnitureService.GetDesigners().Select(designer => new SelectListItem
                    {
                        Text = designer.FullName,
                        Value = designer.DesignerId.ToString()
                    }),
                    Types = FurnitureService.GetTypes().Select(furnitureType => new SelectListItem
                    {
                        Text = furnitureType.Name,
                        Value = furnitureType.FurnitureTypeId.ToString()
                    }),
                }
            });
        }

        //
        // POST: /Admin/Furnitures/Create

        [HttpPost]
        public ActionResult Create(CreateFurnituresViewModel requestedViewModel)
        {
            if (ModelState.IsValid)
            {
                Furniture furniture = Mapper.Map<FurnitureFormViewModel, Furniture>(requestedViewModel.FurnitureForm);

                FurnitureService.Create(furniture);

                Image image = ImageService.Upload(requestedViewModel.ProfileImage, furniture);
                ImageService.Resize(image, FurnitureService.ImageSizes, furniture);

                FurnitureService.SetProfileImage(furniture, image);

                return RedirectToAction("Update", new { id = furniture.FurnitureId });
            }

            requestedViewModel.FurnitureForm.Designers = FurnitureService.GetDesigners().Select(designer => new SelectListItem
            {
                Text = designer.FullName,
                Value = designer.DesignerId.ToString()
            });
            requestedViewModel.FurnitureForm.Types = FurnitureService.GetTypes().Select(furnitureType => new SelectListItem
            {
                Text = furnitureType.Name,
                Value = furnitureType.FurnitureTypeId.ToString()
            });

            return View(requestedViewModel);
        }

        //
        // GET: /Admin/Furnitures/Update/1

        public ActionResult Update(int id)
        {
            Furniture furniture = FurnitureService.GetById(id);

            FurnitureFormViewModel formViewModel = GenerateFurnitureFormViewModel();
            Mapper.Map<Furniture, FurnitureFormViewModel>(furniture, formViewModel);

            if (TempData["ModelStateFile"] != null)
            {
                foreach (var item in (IEnumerable<KeyValuePair<string, ModelState>>)TempData["ModelStateFile"])
                {
                    ModelState.Add(item);
                }
            }

            return View(new UpdateFurnituresViewModel
            {
                Furniture = furniture,
                FurnitureForm = formViewModel
            });
        }

        //
        // POST: /Admin/Furnitures/Update/1

        [HttpPost]
        public ActionResult Update(int id, UpdateFurnituresViewModel requestedViewModel)
        {
            Furniture furniture = FurnitureService.GetById(id);

            if (ModelState.IsValid)
            {
                Mapper.Map<FurnitureFormViewModel, Furniture>(requestedViewModel.FurnitureForm, furniture);

                FurnitureService.Update(furniture);

                return RedirectToAction("Update", new { id = id });
            }

            requestedViewModel.Furniture = furniture;
            requestedViewModel.FurnitureForm.Designers = FurnitureService.GetDesigners().Select(designer => new SelectListItem
            {
                Text = designer.FullName,
                Value = designer.DesignerId.ToString()
            });
            requestedViewModel.FurnitureForm.Types = FurnitureService.GetTypes().Select(furnitureType => new SelectListItem
            {
                Text = furnitureType.Name,
                Value = furnitureType.FurnitureTypeId.ToString()
            });

            return View(requestedViewModel);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            Furniture furniture = FurnitureService.GetById(id);

            List<Image> images = furniture.Images.ToList();
            foreach (int imageId in images.Select(x => x.ImageId))
            {
                Image image = ImageService.GetById(imageId);
                ImageService.Delete(image);
            }

            FurnitureService.Delete(furniture);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult UploadImage(int id, UploadImageViewModel requestedViewModel)
        {
            if (ModelState.IsValid)
            {
                string[] authorziedContentTypes = new string[]{
                    "image/gif", "image/png", "image/jpeg", "image/pjpeg"};

                string contentType = getMimeFromFile(requestedViewModel.File);
                if (!authorziedContentTypes.Any(x => x.Equals(contentType, StringComparison.OrdinalIgnoreCase)))
                {
                    ModelState.AddModelError("File", "Du må kun uploade .gif, .png og .jpg");
                }

                if (ModelState.IsValid)
                {
                    Furniture furniture = FurnitureService.GetById(id);

                    Image image = ImageService.Upload(requestedViewModel.File, furniture);
                    ImageService.Resize(image, FurnitureService.ImageSizes, furniture);

                    if (requestedViewModel.ProfileImage.HasValue && requestedViewModel.ProfileImage.Value)
                        FurnitureService.SetProfileImage(furniture, image);

                    return new RedirectResult(Url.Action("Update", new { id = id }) + "#images");
                }
            }

            TempData["ModelStateFile"] = ModelState.Where(x => x.Key == "File");
            return new RedirectResult(Url.Action("Update", new { id = id }) + "#images");
        }

        public ActionResult UpdateImage(int id, int imageId)
        {
            Furniture furniture = FurnitureService.GetById(id);

            FurnitureService.SetProfileImage(furniture, ImageService.GetById(imageId));

            return new RedirectResult(Url.Action("Update", new { id = id }) + "#images");
        }

        public ActionResult DeleteImage(int id, int imageId)
        {
            Image image = ImageService.GetById(imageId);
            ImageService.Delete(image);

            return new RedirectResult(Url.Action("Update", new { id = id }) + "#images");
        }

        private FurnitureFormViewModel GenerateFurnitureFormViewModel()
        {
            return new FurnitureFormViewModel
            {
                Designers = FurnitureService.GetDesigners().Select(designer => new SelectListItem
                {
                    Text = designer.FullName,
                    Value = designer.DesignerId.ToString()
                }),
                Types = FurnitureService.GetTypes().Select(furnitureType => new SelectListItem
                {
                    Text = furnitureType.Name,
                    Value = furnitureType.FurnitureTypeId.ToString()
                }),
            };
        }

        [DllImport("urlmon.dll", CharSet = CharSet.Unicode, ExactSpelling = true, SetLastError = false)]
        static extern int FindMimeFromData(IntPtr pBC,
            [MarshalAs(UnmanagedType.LPWStr)] string pwzUrl,
            [MarshalAs(UnmanagedType.LPArray, ArraySubType = UnmanagedType.I1, SizeParamIndex = 3)] byte[] pBuffer,
            int cbSize,
            [MarshalAs(UnmanagedType.LPWStr)] string pwzMimeProposed,
            int dwMimeFlags, out IntPtr ppwzMimeOut, int dwReserved);

        public static string getMimeFromFile(HttpPostedFileBase file)
        {
            IntPtr mimeout;

            int MaxContent = (int)file.ContentLength;
            if (MaxContent > 4096) MaxContent = 4096;

            byte[] buf = new byte[MaxContent];
            file.InputStream.Read(buf, 0, MaxContent);
            int result = FindMimeFromData(IntPtr.Zero, file.FileName, buf, MaxContent, null, 0, out mimeout, 0);

            if (result != 0)
            {
                Marshal.FreeCoTaskMem(mimeout);
                return "";
            }

            string mime = Marshal.PtrToStringUni(mimeout);
            Marshal.FreeCoTaskMem(mimeout);

            return mime.ToLower();
        }
    }
}

CmkFurnitures.Web.UI/Controllers/FurnitureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CmkFurnitures.Web.UI.Models;
using CmkFurnitures.Domain.Services;
using CmkFurnitures.Domain;

namespace CmkFurnitures.Web.UI.Controllers
{
    public class FurnitureController : Controller
    {
        protected IFurnitureService FurnitureService;

        public FurnitureController(IFurnitureService funitureService)
        {
            this.FurnitureService = funitureService;
        }

        //
        // GET: /Furniture/Search/

        public ActionResult Search()
        {
            return View(new SearchFurnitureViewModel("Møbler", "furnitures")
            {
                SearchForm = new SearchFurnitureFormViewModel
                {
                    Types = FurnitureService.GetTypes(),
                    Designers = FurnitureService.GetDesigners().Select(x => new KeyValuePair<string, string>(x.FullName, x.DesignerId.ToString()))
                }
            });
        }

        //
        // POST: /Furniture/Search/
        [HttpPost]
        public ActionResult Search(SearchFurnitureFormViewModel requestedViewModel)
        {
            var results = FurnitureService.Search(
                requestedViewModel.PartNumber,
                requestedViewModel.SelectedTypes,
                requestedViewModel.SelectedDesigner,
                requestedViewModel.Year.Min,
                requestedViewModel.Year.Max,
                requestedViewModel.Price.Min,
                requestedViewModel.Price.Max
            );

            if (results.Count(x => x.PartNumber == requestedViewModel.PartNumber) == 1)
            {
                return RedirectToAction("Show", new { id = requestedViewModel.PartNumber });
            }
            else if (results.Count() == 0)
            {
                requestedViewModel.Types = FurnitureService.GetTypes();
                requestedViewModel.Designers = FurnitureService.GetDesigners().Select(x => new KeyValuePair<string, string>(x.FullName, x.DesignerId.ToString()));
                ViewBag.NoResults = true;
                return View("Search", new SearchFurnitureViewModel("Møbler", "furnitures")
                {
                    SearchForm = requestedViewModel
                });
            }

            return View("SearchResult", new SearchResultFurnitureViewModel("Møbler", "furnitures")
            {
                Results = results
            });
        }

        //
        // GET: /Furniture/Show/1

        public ActionResult Show(string id)
        {
            Furniture furniture = FurnitureService.GetByPartNumber(id);

            if (furniture == null)
            {
                return RedirectToActionPermanent("Search");
            }

            return View(new ShowFurnitureViewModel("Møbler", "furnitures")
            {
                Furniture = furniture
            });
        }

        //
        //GET: PartialOnly
        [ChildActionOnly]
        public ActionResult RandomFurniture()
        {
            return PartialView(new RandomFurnitureViewModel
            {
                Furniture = FurnitureService.GetRandom()
            });
        }
    }
}

CmkFurnitures.Web.UI/Views/Furniture/RandomFurniture.cshtml
@model RandomFurnitureViewModel
<section class="highlighted-furniture">
    <div class="container">
        <img src="@Url.Content(Model.Furniture.ProfileImage.GetResizedImage(120, 90).VirtualPath)" alt="møbel" />
        <dl>
            <dt>Møbel serie: </dt>
            <dd>
                @Model.Furniture.FurnitureType.Name
            </dd>
            <dt>Designer: </dt>
            <dd>
                @Model.Furniture.Designer.FullName
            </dd>
            <dt>Design år: </dt>
            <dd>
                @Model.Furniture.DesignYear
            </dd>
            <dt>Pris: </dt>
            <dd>
                @string.Format("{0,10:#,##0.00} kr.", Model.Furniture.Price)
            </dd>
        </dl>
        <a href="@Url.Action("Show", "Furniture", new { id = Model.Furniture.PartNumber })">mere info</a>
    </div>
</section>

CmkFurnitures.Web.UI/Views/Furniture/Search.cshtml
@model SearchFurnitureViewModel
@{
    ViewBag.Title = "Search";
}
<div class="funiture-search">
    @if (ViewBag.NoResults != null && ViewBag.NoResults)
    {
        <p class="no-results">
            Der er desværre ikke nogen emner der matcher dine kriterier.<br />
            Vi anbefaler at du udvider din søgning og prøver igen.
        </p>
    }
    @{ Html.RenderPartial("_FurnitureSearchForm", Model.SearchForm); }
</div>

CmkFurnitures.Web.UI/Views/Furniture/SearchResult.cshtml
@model SearchResultFurnitureViewModel
<div class="furniture-search-results">
    @foreach (var item in Model.Results)
    {
        <section>
            <a href="@Url.Action("Show", "Furniture", new { id = item.PartNumber })">
                <img src="@Url.Content(item.ProfileImage.VirtualPath)" alt="sofa" />
                <div>
                    <h2>
                        @item.Name</h2>
                    <p>
                        @if (item.Text.Length > 187)
                        {
                            @item.Text.Substring(0, 183) <text> ...</text>
                        }
                        else
                        {
                            @item.Text
                        }
                    </p>
                </div>
            </a>
        </section>
        <div class="seperator">
        </div>
    }
</div>

CmkFurnitures.Web.UI/Views/Furniture/Show.cshtml
@model ShowFurnitureViewModel
<article class="funiture-display">
    <h1>
        @Model.Furniture.Name</h1>
    <div class="images">
        <img alt="@Model.Furniture.Name" id="large" data-thumb="@Url.Content(Model.Furniture.ProfileImage.GetResizedImage(50, 50).VirtualPath)" src="@Url.Content(Model.Furniture.ProfileImage.GetResizedImage(300, 225).VirtualPath)" />
        <div class="others">
            <h1>
                Andre varianter</h1>
            @foreach (var item in Model.Furniture.Images.Where(x => x.ImageId != Model.Furniture.ProfileImageId))
            {
                <img alt="@Model.Furniture.Name" class="thumb" data-large="@Url.Content(item.GetResizedImage(300, 225).VirtualPath)" src="@Url.Content(item.GetResizedImage(50, 50).VirtualPath)" />
            }
        </div>
    </div>
    <div class="specifications">
        <p>
            @Model.Furniture.Text
        </p>
        <dl>
            <dt>Pris: </dt>
            <dd>
                @string.Format("{0,10:#,##0.00} kr.", Model.Furniture.Price)
            </dd>
            <dt>Designer: </dt>
            <dd>
                @Model.Furniture.Designer.FullName
            </dd>
            <dt>Møbel serie: </dt>
            <dd>
                @Model.Furniture.FurnitureType.Name
            </dd>
            <dt>Design år: </dt>
            <dd>
                @Model.Furniture.DesignYear
            </dd>
            <dt>Varenummer: </dt>
            <dd>
                @Model.Furniture.PartNumber
            </dd>
        </dl>
    </div>
</article>
@section CustomJavascript{
    <script>
        $(function () {

            function swapLarge(thumb) {
                var $thumb = $(thumb),
                    $large = $("#large"),

                    tempThumbSrc = $large.data("thumb"),
                    tempLargeSrc = $large.attr("src");

                $large.attr("src", $thumb.data("large"));
                $large.data("thumb", $thumb.attr("src"));

                $thumb.attr("src", tempThumbSrc);
                $thumb.data("large", tempLargeSrc);
            }

            $(".thumb").click(function (e) {
                swapLarge(this);
            });

        });
    </script>
}

CmkFurnitures.Web.UI/Views/Furniture/_FurnitureSearchForm.cshtml
@model SearchFurnitureFormViewModel
@using (Html.BeginForm("Search", "Furniture", FormMethod.Post, null))
{
    <div class="control-group">
        <label>
            Vare nummer:</label>
        <div class="controls">
            @Html.TextBoxFor(x => x.PartNumber)
            <button type="submit" class="inline-search">
                Søg</button>
        </div>
        @Html.ValidationMessageFor(x => x.PartNumber)
    </div>
    <div class="control-group">
        <label>
            Møbel serie:</label>
        <div class="controls">
            @foreach (var item in Model.Types)
            {
                <div class="checkbox-group">
                    <input type="checkbox" value="@item.FurnitureTypeId" name="SearchForm.SelectedTypes"  />
                    <label>
                        @item.Name</label>
                </div>
            }
        </div>
    </div>
    <div class="control-group">
        <label>
            Designer:</label>
        <div class="controls">
            @Html.DropDownListFor(x => x.SelectedDesigner, new SelectList(Model.Designers, "Value", "Key"), "Alle")
        </div>
    </div>
    <div class="control-group">
        <label>
            Design år:</label>
        <div class="controls">
            <div class="inline-group">
                <label>
                    min:</label>
                @Html.TextBoxFor(x => x.Year.Min)
            </div>
            <div class="inline-group">
                <label>
                    max:</label>
                @Html.TextBoxFor(x => x.Year.Max)
            </div>
        </div>
    </div>
    <div class="control-group">
        <label>
            Pris:</label>
        <div class="controls">
            <div class="inline-group">
                <label>
                    min:</label>
                @Html.TextBoxFor(x => x.Price.Min)
            </div>
            <div class="inline-group">
                <label>
                    max:</label>
                @Html.TextBoxFor(x => x.Price.Min)
            </div>
        </div>
    </div>
    <div class="control-buttons-right">
        <button type="submit">
            Søg</button>
    </div>
}