CmkFurnitures.Web.UI/Areas/Admin/Controllers/DesignersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CmkFurnitures.Domain.Services;
using CmkFurnitures.Web.UI.Areas.Admin.Models;
using CmkFurnitures.Domain;
using AutoMapper;

namespace CmkFurnitures.Web.UI.Areas.Admin.Controllers
{
    [Authorize]
    public class DesignersController : BaseController
    {
        protected IFurnitureService FurnitureService;

        public DesignersController(IFurnitureService funitureService)
        {
            this.FurnitureService = funitureService;
        }

        //
        // GET: /Admin/Designer/

        public ActionResult Index()
        {
            return View(new IndexDesignersViewModel
            {
                Designers = FurnitureService.GetDesigners()
            });
        }

        //
        // GET: /Admin/Designer/Create

        public ActionResult Create()
        {
            return View(new CreateDesignersViewModel
            {
                DesignerForm = new DesignerFormViewModel()
            });
        }


        //
        // POST: /Admin/Designer/Create

        [HttpPost]
        public ActionResult Create(CreateDesignersViewModel requestedViewModel)
        {
            if (ModelState.IsValid)
            {
                FurnitureService.CreateDesigner(requestedViewModel.DesignerForm.FirstName, requestedViewModel.DesignerForm.LastName);

                return RedirectToAction("Index");
            }

            return View(requestedViewModel);
        }

        //
        // GET: /Admin/Designer/Update/1

        public ActionResult Update(int id)
        {
            Designer designer = FurnitureService.GetDesignerById(id);

            return View(new UpdateDesignersViewModel
            {
                DesignerForm = Mapper.Map<Designer, DesignerFormViewModel>(designer)
            });
        }


        //
        // POST: /Admin/Designer/Update/1

        [HttpPost]
        public ActionResult Update(int id, UpdateDesignersViewModel requestedViewModel)
        {
            Designer designer = FurnitureService.GetDesignerById(id);

            if (ModelState.IsValid)
            {
                FurnitureService.UpdateDesigner(id, requestedViewModel.DesignerForm.FirstName, requestedViewModel.DesignerForm.LastName);

                return RedirectToAction("Index");
            }

            return View(requestedViewModel);
        }

        public ActionResult Delete(int id)
        {
            Designer designer = FurnitureService.GetDesignerById(id);

            if (designer == null)
            {
                return View("NotFound");
            }
            else if (designer.Furnitures.Count() > 0)
            {
                return View("NotDeleted", new NotDeletedDesignerViewModel
                {
                    Designer = designer
                });
            }
            else
            {
                FurnitureService.DeleteDesigner(designer);
                return View("Deleted");
            }
        }
    }
}

CmkFurnitures.Web.UI/Areas/Admin/Views/Designers/Create.cshtml
@model CreateDesignersViewModel
@{
    ViewBag.JavaScriptValidation = true;
}
<div class="page-header">
    <h2>
        Opret designer</h2>
</div>
@using (Html.BeginForm("Create", "Designers", FormMethod.Post, new { @class = "form-horizontal" })){
    @Html.PartialFor(model => model.DesignerForm, "_DesignerForm")
}

CmkFurnitures.Web.UI/Areas/Admin/Views/Designers/Deleted.cshtml
@{
    ViewBag.Title = "Deleted";
}
<div class="page-header">
    <h2>
        Designeren er slettet</h2>
</div>
<p>
    Designeren er blevet slettet fra databasen
</p>
<p>
    @Html.ActionLink("Gå til oversigten", "Index")
</p>

CmkFurnitures.Web.UI/Areas/Admin/Views/Designers/Index.cshtml
@model IndexDesignersViewModel
<div class="page-header">
    <p class="pull-right">
        @Html.ActionLink("Opret nyt designer", "Create", null, new { @class = "btn btn-success" })
    </p>
    <h2>
        Oversigt over designere</h2>
</div>
<table class="table table-stripe table-hover">
    <tr>
        <th>
            Fornavn
        </th>
        <th>
            Efternavn
        </th>
        <th>
            Antal møbler
        </th>
        <th>
        </th>
    </tr>
    @foreach (var item in Model.Designers)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @item.Furnitures.Count()
            </td>
            <td>
                @Html.ActionLink("Rediger", "Update", new { id = item.DesignerId }) |
                @Html.ActionLink("Slet", "Delete", new { id = item.DesignerId })
            </td>
        </tr>
    }
</table>

CmkFurnitures.Web.UI/Areas/Admin/Views/Designers/NotDeleted.cshtml
@model CmkFurnitures.Web.UI.Areas.Admin.Models.NotDeletedDesignerViewModel
@{
    ViewBag.Title = "NotDeleted";
}
<div class="page-header">
    <h2>
        Kunne ikke slette designeren</h2>
</div>
<p>
    Det var ikke muligt at slette designeren <b>@Model.Designer.FullName</b>
</p>
@if (Model.Designer.Furnitures.Count() > 0)
{
    <p>
        Der findes referencer til designeren..
    </p>
}
@if (Model.Designer.Furnitures.Count() > 0)
{
    <h3>
        Møbler der har reference til designeren
    </h3>
    Html.RenderPartial("~/Areas/Admin/Views/Furnitures/_FurnituresTableView.cshtml", Model.Designer.Furnitures);
}

CmkFurnitures.Web.UI/Areas/Admin/Views/Designers/NotFound.cshtml
@{
    ViewBag.Title = "Deleted";
}
<div class="page-header">
    <h2>
        Designeren blev ikke fundet</h2>
</div>
<p>
    Designeren fandtes ikke i databasen..
</p>
<p>
    @Html.ActionLink("Gå til oversigten", "Index")
</p>

CmkFurnitures.Web.UI/Areas/Admin/Views/Designers/Update.cshtml
@model UpdateDesignersViewModel
@{
    ViewBag.JavaScriptValidation = true;
}
<div class="page-header">
    <h2>
        Rediger designer</h2>
</div>
@using (Html.BeginForm("Update", "Designers", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.PartialFor(model => model.DesignerForm, "_DesignerForm")
}

CmkFurnitures.Web.UI/Areas/Admin/Views/Designers/_DesignerForm.cshtml
@model DesignerFormViewModel
    @Html.ValidationSummary(true)
    <div class="control-group">
        <label class="control-label">
            Fornavn</label>
        <div class="controls">
            @Html.EditorFor(model => model.FirstName)
            @Html.ValidationMessageFor(model => model.FirstName)
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">
            Efternavn</label>
        <div class="controls">
            @Html.EditorFor(model => model.LastName)
            @Html.ValidationMessageFor(model => model.LastName)
        </div>
    </div>
    <div class="form-actions">
        <button type="submit" class="btn btn-primary">
            Gem ændringer</button>
        <button type="button" class="btn" onclick="location.href='@Url.Action("Index", "Designers")'">
            Annuler</button>
    </div>