CmkFurnitures.Web.UI/Areas/Admin/Controllers/FurnituresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using CmkFurnitures.Web.UI.Areas.Admin.Models;
using CmkFurnitures.Domain.Services;
using CmkFurnitures.Domain;
using System.ComponentModel.DataAnnotations;
using System.Runtime.InteropServices;

namespace CmkFurnitures.Web.UI.Areas.Admin.Controllers
{
    [Authorize]
    public class FurnituresController : BaseController
    {
        protected IFurnitureService FurnitureService;
        protected IImageService ImageService;

        public FurnituresController(IFurnitureService funitureService, IImageService imageService)
        {
            this.FurnitureService = funitureService;
            this.ImageService = imageService;
        }

        //
        // GET: /Admin/Furnitures/

        public ActionResult Index()
        {
            return View(new IndexFurnituresViewModel
            {
                Furnitures = FurnitureService.GetAll()
            });
        }

        //
        // GET: /Admin/Furnitures/Create

        public ActionResult Create()
        {
            return View(new CreateFurnituresViewModel
            {
                FurnitureForm = new FurnitureFormViewModel
                {
                    Designers = FurnitureService.GetDesigners().Select(designer => new SelectListItem
                    {
                        Text = designer.FullName,
                        Value = designer.DesignerId.ToString()
                    }),
                    Types = FurnitureService.GetTypes().Select(furnitureType => new SelectListItem
                    {
                        Text = furnitureType.Name,
                        Value = furnitureType.FurnitureTypeId.ToString()
                    }),
                }
            });
        }

        //
        // POST: /Admin/Furnitures/Create

        [HttpPost]
        public ActionResult Create(CreateFurnituresViewModel requestedViewModel)
        {
            if (ModelState.IsValid)
            {
                Furniture furniture = Mapper.Map<FurnitureFormViewModel, Furniture>(requestedViewModel.FurnitureForm);

                FurnitureService.Create(furniture);

                Image image = ImageService.Upload(requestedViewModel.ProfileImage, furniture);
                ImageService.Resize(image, FurnitureService.ImageSizes, furniture);

                FurnitureService.SetProfileImage(furniture, image);

                return RedirectToAction("Update", new { id = furniture.FurnitureId });
            }

            requestedViewModel.FurnitureForm.Designers = FurnitureService.GetDesigners().Select(designer => new SelectListItem
            {
                Text = designer.FullName,
                Value = designer.DesignerId.ToString()
            });
            requestedViewModel.FurnitureForm.Types = FurnitureService.GetTypes().Select(furnitureType => new SelectListItem
            {
                Text = furnitureType.Name,
                Value = furnitureType.FurnitureTypeId.ToString()
            });

            return View(requestedViewModel);
        }

        //
        // GET: /Admin/Furnitures/Update/1

        public ActionResult Update(int id)
        {
            Furniture furniture = FurnitureService.GetById(id);

            FurnitureFormViewModel formViewModel = GenerateFurnitureFormViewModel();
            Mapper.Map<Furniture, FurnitureFormViewModel>(furniture, formViewModel);

            if (TempData["ModelStateFile"] != null)
            {
                foreach (var item in (IEnumerable<KeyValuePair<string, ModelState>>)TempData["ModelStateFile"])
                {
                    ModelState.Add(item);
                }
            }

            return View(new UpdateFurnituresViewModel
            {
                Furniture = furniture,
                FurnitureForm = formViewModel
            });
        }

        //
        // POST: /Admin/Furnitures/Update/1

        [HttpPost]
        public ActionResult Update(int id, UpdateFurnituresViewModel requestedViewModel)
        {
            Furniture furniture = FurnitureService.GetById(id);

            if (ModelState.IsValid)
            {
                Mapper.Map<FurnitureFormViewModel, Furniture>(requestedViewModel.FurnitureForm, furniture);

                FurnitureService.Update(furniture);

                return RedirectToAction("Update", new { id = id });
            }

            requestedViewModel.Furniture = furniture;
            requestedViewModel.FurnitureForm.Designers = FurnitureService.GetDesigners().Select(designer => new SelectListItem
            {
                Text = designer.FullName,
                Value = designer.DesignerId.ToString()
            });
            requestedViewModel.FurnitureForm.Types = FurnitureService.GetTypes().Select(furnitureType => new SelectListItem
            {
                Text = furnitureType.Name,
                Value = furnitureType.FurnitureTypeId.ToString()
            });

            return View(requestedViewModel);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            Furniture furniture = FurnitureService.GetById(id);

            List<Image> images = furniture.Images.ToList();
            foreach (int imageId in images.Select(x => x.ImageId))
            {
                Image image = ImageService.GetById(imageId);
                ImageService.Delete(image);
            }

            FurnitureService.Delete(furniture);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult UploadImage(int id, UploadImageViewModel requestedViewModel)
        {
            if (ModelState.IsValid)
            {
                string[] authorziedContentTypes = new string[]{
                    "image/gif", "image/png", "image/jpeg", "image/pjpeg"};

                string contentType = getMimeFromFile(requestedViewModel.File);
                if (!authorziedContentTypes.Any(x => x.Equals(contentType, StringComparison.OrdinalIgnoreCase)))
                {
                    ModelState.AddModelError("File", "Du må kun uploade .gif, .png og .jpg");
                }

                if (ModelState.IsValid)
                {
                    Furniture furniture = FurnitureService.GetById(id);

                    Image image = ImageService.Upload(requestedViewModel.File, furniture);
                    ImageService.Resize(image, FurnitureService.ImageSizes, furniture);

                    if (requestedViewModel.ProfileImage.HasValue && requestedViewModel.ProfileImage.Value)
                        FurnitureService.SetProfileImage(furniture, image);

                    return new RedirectResult(Url.Action("Update", new { id = id }) + "#images");
                }
            }

            TempData["ModelStateFile"] = ModelState.Where(x => x.Key == "File");
            return new RedirectResult(Url.Action("Update", new { id = id }) + "#images");
        }

        public ActionResult UpdateImage(int id, int imageId)
        {
            Furniture furniture = FurnitureService.GetById(id);

            FurnitureService.SetProfileImage(furniture, ImageService.GetById(imageId));

            return new RedirectResult(Url.Action("Update", new { id = id }) + "#images");
        }

        public ActionResult DeleteImage(int id, int imageId)
        {
            Image image = ImageService.GetById(imageId);
            ImageService.Delete(image);

            return new RedirectResult(Url.Action("Update", new { id = id }) + "#images");
        }

        private FurnitureFormViewModel GenerateFurnitureFormViewModel()
        {
            return new FurnitureFormViewModel
            {
                Designers = FurnitureService.GetDesigners().Select(designer => new SelectListItem
                {
                    Text = designer.FullName,
                    Value = designer.DesignerId.ToString()
                }),
                Types = FurnitureService.GetTypes().Select(furnitureType => new SelectListItem
                {
                    Text = furnitureType.Name,
                    Value = furnitureType.FurnitureTypeId.ToString()
                }),
            };
        }

        [DllImport("urlmon.dll", CharSet = CharSet.Unicode, ExactSpelling = true, SetLastError = false)]
        static extern int FindMimeFromData(IntPtr pBC,
            [MarshalAs(UnmanagedType.LPWStr)] string pwzUrl,
            [MarshalAs(UnmanagedType.LPArray, ArraySubType = UnmanagedType.I1, SizeParamIndex = 3)] byte[] pBuffer,
            int cbSize,
            [MarshalAs(UnmanagedType.LPWStr)] string pwzMimeProposed,
            int dwMimeFlags, out IntPtr ppwzMimeOut, int dwReserved);

        public static string getMimeFromFile(HttpPostedFileBase file)
        {
            IntPtr mimeout;

            int MaxContent = (int)file.ContentLength;
            if (MaxContent > 4096) MaxContent = 4096;

            byte[] buf = new byte[MaxContent];
            file.InputStream.Read(buf, 0, MaxContent);
            int result = FindMimeFromData(IntPtr.Zero, file.FileName, buf, MaxContent, null, 0, out mimeout, 0);

            if (result != 0)
            {
                Marshal.FreeCoTaskMem(mimeout);
                return "";
            }

            string mime = Marshal.PtrToStringUni(mimeout);
            Marshal.FreeCoTaskMem(mimeout);

            return mime.ToLower();
        }
    }
}

CmkFurnitures.Web.UI/Controllers/FurnitureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CmkFurnitures.Web.UI.Models;
using CmkFurnitures.Domain.Services;
using CmkFurnitures.Domain;

namespace CmkFurnitures.Web.UI.Controllers
{
    public class FurnitureController : Controller
    {
        protected IFurnitureService FurnitureService;

        public FurnitureController(IFurnitureService funitureService)
        {
            this.FurnitureService = funitureService;
        }

        //
        // GET: /Furniture/Search/

        public ActionResult Search()
        {
            return View(new SearchFurnitureViewModel("Møbler", "furnitures")
            {
                SearchForm = new SearchFurnitureFormViewModel
                {
                    Types = FurnitureService.GetTypes(),
                    Designers = FurnitureService.GetDesigners().Select(x => new KeyValuePair<string, string>(x.FullName, x.DesignerId.ToString()))
                }
            });
        }

        //
        // POST: /Furniture/Search/
        [HttpPost]
        public ActionResult Search(SearchFurnitureFormViewModel requestedViewModel)
        {
            var results = FurnitureService.Search(
                requestedViewModel.PartNumber,
                requestedViewModel.SelectedTypes,
                requestedViewModel.SelectedDesigner,
                requestedViewModel.Year.Min,
                requestedViewModel.Year.Max,
                requestedViewModel.Price.Min,
                requestedViewModel.Price.Max
            );

            if (results.Count(x => x.PartNumber == requestedViewModel.PartNumber) == 1)
            {
                return RedirectToAction("Show", new { id = requestedViewModel.PartNumber });
            }
            else if (results.Count() == 0)
            {
                requestedViewModel.Types = FurnitureService.GetTypes();
                requestedViewModel.Designers = FurnitureService.GetDesigners().Select(x => new KeyValuePair<string, string>(x.FullName, x.DesignerId.ToString()));
                ViewBag.NoResults = true;
                return View("Search", new SearchFurnitureViewModel("Møbler", "furnitures")
                {
                    SearchForm = requestedViewModel
                });
            }

            return View("SearchResult", new SearchResultFurnitureViewModel("Møbler", "furnitures")
            {
                Results = results
            });
        }

        //
        // GET: /Furniture/Show/1

        public ActionResult Show(string id)
        {
            Furniture furniture = FurnitureService.GetByPartNumber(id);

            if (furniture == null)
            {
                return RedirectToActionPermanent("Search");
            }

            return View(new ShowFurnitureViewModel("Møbler", "furnitures")
            {
                Furniture = furniture
            });
        }

        //
        //GET: PartialOnly
        [ChildActionOnly]
        public ActionResult RandomFurniture()
        {
            return PartialView(new RandomFurnitureViewModel
            {
                Furniture = FurnitureService.GetRandom()
            });
        }
    }
}

CmkFurnitures.Web.UI/Areas/Admin/Views/Furnitures/Create.cshtml
@model CreateFurnituresViewModel
@{
    ViewBag.Title = "Update";
}
<div class="page-header">
    <h2>
        Opret møbel</h2>
</div>
@using (Html.BeginForm("Create", "Furnitures", FormMethod.Post, new { @class = "form-horizontal", enctype = "multipart/form-data" }))
{
    @Html.PartialFor(model => model.FurnitureForm, "_FurnitureForm")

    <div class="control-group">
        <label class="control-label">
            Profilbillede:
        </label>
        <div class="controls">
            <input type="file" name="ProfileImage" id="ProfileImage" />
        </div>
    </div>
    
    <div class="form-actions">
        <button type="submit" class="btn btn-primary">
            Gem ændringer</button>
        <button type="button" class="btn" onclick="location.href='@Url.Action("Index", "Furnitures")'">
            Annuler</button>
    </div>
}

CmkFurnitures.Web.UI/Areas/Admin/Views/Furnitures/Index.cshtml
@model IndexFurnituresViewModel
<div class="page-header">
    @Html.ActionLink("Opret nyt møbel", "Create", null, new { @class = "btn btn-success  pull-right" })
    <h2>
        Oversigt over møbler</h2>
</div>
@{ Html.RenderPartial("_FurnituresTableView", Model.Furnitures); }

CmkFurnitures.Web.UI/Areas/Admin/Views/Furnitures/Update.cshtml
@model UpdateFurnituresViewModel
@{
    ViewBag.Title = "Update";
    ViewBag.JavaScriptValidation = true;
}
<div class="page-header">
    <h2>
        Rediger @Model.Furniture.Name</h2>
</div>
<ul class="nav nav-tabs" id="furniture-update-tabs">
    <li><a href="#home" data-target="#home" data-toggle="tab">Information</a> </li>
    <li><a href="#images" data-target="#images" data-toggle="tab">Billeder</a> </li>
    <li><a href="#delete" data-target="#delete" data-toggle="tab">Slet møbel</a> </li>
</ul>
<div class="tab-content">
    <div id="home" class="tab-pane">
        @using (Html.BeginForm("Update", "Furnitures", new { id = Model.Furniture.FurnitureId }, FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.PartialFor(model => model.FurnitureForm, "_FurnitureForm")
            <div class="form-actions">
                <button type="submit" class="btn btn-primary">
                    Gem ændringer</button>
                <button type="button" class="btn" onclick="location.href='@Url.Action("Index", "Furnitures")'">
                    Annuler</button>
            </div>
        }
    </div>
    <div id="images" class="tab-pane">
        <div>
            @using (Html.BeginForm("UploadImage", "Furnitures", new { id = Model.Furniture.FurnitureId }, FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-inline" }))
            {
                <div class="control-group">
                    <input type="file" name="File" class="input-xxlarge" />
                    <label class="checkbox">
                        <input type="checkbox" name="ProfileImage" value="true">
                        Gør til profilbillede
                    </label>
                </div>
                if (ViewContext.ViewData.ModelState.Any(x => x.Key == "File"))
                {
                <div>
                    @Html.ValidationMessage("File")
                </div>
                <button type="submit" class="btn btn-warning">
                    Upload billede</button>
                }
                else
                {
                <button type="submit" class="btn btn-success">
                    Upload billede</button>
                }
            }
        </div>
        <hr />
        @{ 
            int numberOfImagesPerRow = 4; 
        }
        @for (int i = 0; i < Convert.ToInt32(Math.Ceiling((decimal)Model.Furniture.Images.Count() / numberOfImagesPerRow)); i++)
        {
            <div class="row-fluid show-grid">
                @foreach (var image in Model.Furniture.Images.Skip(i * numberOfImagesPerRow).Take(numberOfImagesPerRow))
                {
                    var resizedImage = image.GetResizedImage(300, 225);
                    <div class="span3">
                        <img src="@Url.Content(resizedImage.VirtualPath)" class="img-polaroid full-width" alt="@Model.Furniture.Name" />
                        @if (Model.Furniture.ProfileImageId.Equals(image.ImageId))
                        {
                            <a href="#" class="btn btn-info disabled" rel="tooltip" title="Dette billede er valgt som profilbillede der bliver vidst flest gange på siden">
                                Valgt som profilbillede</a>
                            <a href="#" class="deleteBtn btn btn-danger disabled" rel="tooltip" title="Det er ikke muligt at slette et profilbillede. Upload et nyt og vælg det som profilbillede">
                                Slet</a>
                        }
                        else
                        {
                            <a href="@Url.Action("UpdateImage", "Furnitures", new { id = Model.Furniture.FurnitureId, imageId = image.ImageId })" class="btn">
                                Vælg som profilbillede</a>
                            <a href="@Url.Action("DeleteImage", "Furnitures", new { id = Model.Furniture.FurnitureId, imageId = image.ImageId })" class="btn btn-danger">
                                Slet</a>
                        }
                    </div>
                }
            </div>
        }
    </div>
    <div id="delete" class="tab-pane">
        @using (Html.BeginForm("Delete", "Furnitures", new { id = Model.Furniture.FurnitureId }))
        {
            <p>
                Er du sikker? Kan ikke fortrydes
            </p>
                
            <button type="submit" class="btn btn-danger">
                Ja, slet</button>
                
                
            <button id="cancel-deleted" class="btn">
                Annuler</button>

        }
    </div>
</div>
@section CustomJavascript{
    <script>
        $(function () {
            $('#cancel-deleted').click(function () {
                $('#furniture-update-tabs a:first').tab('show')
                return false;
            });
            $('.show-grid').tooltip({
                selector: "a[rel=tooltip]"
            })

            if (document.location.hash) {
                $('#furniture-update-tabs a[data-target=' + document.location.hash + ']').tab('show');
            } else {
                $('#furniture-update-tabs a:first').tab('show');
            }
        })
    </script>
}

CmkFurnitures.Web.UI/Areas/Admin/Views/Furnitures/_FurnitureForm.cshtml
@model FurnitureFormViewModel
@Html.ValidationSummary(true)
<div class="control-group">
    <label class="control-label" for="inputEmail">
        Varenummer</label>
    <div class="controls">
        @Html.EditorFor(model => model.PartNumber)
        @Html.ValidationMessageFor(model => model.PartNumber)
    </div>
</div>
<div class="control-group">
    <label class="control-label" for="inputEmail">
        Navn</label>
    <div class="controls">
        @Html.EditorFor(model => model.Name)
        @Html.ValidationMessageFor(model => model.Name)
    </div>
</div>
<div class="control-group">
    <label class="control-label" for="inputEmail">
        Designer</label>
    <div class="controls">
        @Html.DropDownListFor(model => model.DesignerId, new SelectList(Model.Designers, "Value", "Text", Model.DesignerId), "Vælg designer...")
        @Html.ValidationMessageFor(model => model.DesignerId)
        <a href="@Url.Action("Create", "Designers")">Tilføj en ny designer</a>
    </div>
</div>
<div class="control-group">
    <label class="control-label" for="inputEmail">
        Type</label>
    <div class="controls">
        @Html.DropDownListFor(model => model.FurnitureTypeId, new SelectList(Model.Types, "Value", "Text", Model.FurnitureTypeId), "Vælg type..")
        @Html.ValidationMessageFor(model => model.FurnitureTypeId)
    </div>
</div>
<div class="control-group">
    <label class="control-label" for="inputEmail">
        Årgang</label>
    <div class="controls">
        @Html.EditorFor(model => model.DesignYear)
        @Html.ValidationMessageFor(model => model.DesignYear)
    </div>
</div>
<div class="control-group">
    <label class="control-label" for="inputEmail">
        Pris</label>
    <div class="controls">
        @Html.EditorFor(model => model.Price)
        @Html.ValidationMessageFor(model => model.Price)
    </div>
</div>
<div class="control-group">
    <label class="control-label" for="inputEmail">
        Beskrivelse</label>
    <div class="controls">
        @Html.TextAreaFor(model => model.Text, new { rows = 4, @class = "input-xxlarge" })
        @Html.ValidationMessageFor(model => model.Text)
    </div>
</div>

CmkFurnitures.Web.UI/Areas/Admin/Views/Furnitures/_FurnituresTableView.cshtml
@model IEnumerable<CmkFurnitures.Domain.Furniture>
<table class="table table-stripe table-hover">
    <tr>
        <th>
        </th>
        <th>
            Navn
        </th>
        <th>
            Designer
        </th>
        <th>
            År
        </th>
        <th>
            Pris
        </th>
        <th>
            Type
        </th>
        <th>
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                <img src="@Url.Content(item.ProfileImage.GetResizedImage(120, 90).VirtualPath)" alt="@item.Name" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Designer.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DesignYear)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FurnitureType.Name)
            </td>
            <td>
                <a href="@Url.Action("Update", "Furnitures", new { id = item.FurnitureId })">Rediger</a>
                |
                <a href="@Url.Action("Update", "Furnitures", new { id = item.FurnitureId })#delete">Slet</a>
            </td>
        </tr>
    }
</table>